version: '3'

services:
  angular-frontend:
    image: khalsiaziz/angular-app:latest  # Replace with your correct image and tag
    container_name: angular-frontend
    restart: always
    ports:
      - '80:80'  # Mapping port 80 inside the container to port 80 on the host machine
